export const tableItemData = [
  {
    id: 1,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
  {
    id: 2,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
  {
    id: 3,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
  {
    id: 4,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
  {
    id: 5,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
  {
    id: 6,
    imageURL: "/mini-cooper.png",
    label: "Mini Cooper 2020",
    reservation: "11/07",
    isAvailable: true,
    rating: 5,
  },
];
